#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include "Algebra.h"
#include "Geometry.h"
#include <vector>
#include <wx/filedlg.h>
#include <fstream>
#include <limits>
#include <wx/colordlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/numdlg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button_loadfileOnButtonClick( wxCommandEvent& event );
		void m_button_savefileOnButtonClick( wxCommandEvent& event );
		void m_slider_rotationXOnScroll( wxScrollEvent& event );
		void m_slider_rotationYOnScroll( wxScrollEvent& event );
		void m_slider_rotationZOnScroll( wxScrollEvent& event );
		void m_slider_translationXOnScroll( wxScrollEvent& event );
		void m_slider_translationYOnScroll( wxScrollEvent& event );
		void m_slider_translationZOnScroll( wxScrollEvent& event );
		void m_slider_scaleXOnScroll( wxScrollEvent& event );
		void m_slider_scaleYOnScroll( wxScrollEvent& event );
		void m_slider_scaleZOnScroll( wxScrollEvent& event );
		void m_slider_spacingOnScroll( wxScrollEvent& event );
		void m_button_color_oneOnButtonClick( wxCommandEvent& event );
		void m_button_color_twoOnButtonClick( wxCommandEvent& event );
		void m_button_animateOnButtonClick( wxCommandEvent& event );
		void m_panelOnSize( wxSizeEvent& event );
		void m_timerOnTimer( wxTimerEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void Repaint();
		int object_num;
		std::vector<Line> lines;
		std::vector<Sphere> spheres;
		double rotationX = 0, rotationY = 0, rotationZ = 0;
		double translationX = 0, translationY = 0, translationZ = 0;
		double scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0;
		double spacing = 5.0;
		wxColor color_one = wxColor(242, 28, 71), color_two = wxColor(28, 156, 242);
		bool animate = false;
		int timer = 0;
		wxBitmap to_save;
};

#endif // __GUIMyFrame1__
